# config/config.yaml
data:
  movielens_path: "data/raw/ml-100k"
  test_size: 0.2
  min_rating_threshold: 3.0  
  temporal_split: false
  stratified_split: false
  min_train_items: 5
  use_confidence_weights: false
  random_state: 42

models:
  pmf:
    algorithm: "svd"
    n_factors: 50
    n_epochs: 20
    learning_rate: 0.005
    regularization: 0.02
    biased: false
    reg_pu: null
    reg_qi: null
    random_state: 42
    verbose: true
    
  bpr:
    algorithm: "bpr"
    factors: 100
    iterations: 1000
    learning_rate: 0.01
    regularization: 5.0e-4
    num_threads: 0
    dtype: "float32"
    random_state: 42
    verify_negative_samples: false
    
  lightfm:
    no_components: 100
    learning_rate: 0.01 
    loss: 'warp'
    max_sampled: 10
    item_alpha: 1.0e-6
    user_alpha: 1.0e-6
    epochs: 50
    num_threads: 20
    random_state: 42

optimization:
  run_optimization: true
  run_lightfm: true
  n_trials: 20
  timeout: 900
  n_jobs: 4
  
evaluation:
  k_values: [5, 10, 20]
  max_eval_users: 1000
  calc_diversity: true
  calc_confidence: false
  
output:
  save_models: true
  save_plots: true
  save_predictions: false
  results_dir: "results"
  
advanced:
  ensemble:
    enabled: false
    models: ["pmf", "bpr"]
    method: "weighted"
  
  cross_validation:
    enabled: false
    n_folds: 5
    
  time_based_evaluation:
    enabled: false
    n_windows: 5